export const warlordData = [
  {
    rank: "S ",
    skillName: " 강동 소패왕 ",
    warLords: [" 손책 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투에서 일반 공격 후 35%의 확률로 목표에게 추가로 맹공(피해율 96%→192%) 발동 및 단일 아군 대상의 병력 회복(치료율 28%→56%, 무력의 영향). 자신이 주장일 때 전투 시작 후 2번째 턴까지 단일 적군 대상이 처음 받는 피해 15%→30% 증가 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 강직한 마음 ",
    warLords: [" 하후돈 "],
    type: " 패시브 ",
    target: " 적군 다수(2명) ",
    percentage: " 100% ",
    desc: " 전투 중 자신의 통솔 19→38 증가, 무기 피해를 입으면 40%의 확률로 적군 다수 대상(2명)에게 무기 피해(피해율 42%→84%)",
  },
  {
    rank: "S ",
    skillName: " 금털의 깃발 ",
    warLords: [" 감녕 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 자신의 회심 확률 25%→50%(발동 시 무기 피해 100% 증가) 및 회심 피해 10%→20% 증가. 자신이 주장일 때 우군 다수 대상(2명)의 회심 확률 2.5%→5%와 회심 피해 5%→10% 증가 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 남만두목 ",
    warLords: [" 맹획 "],
    type: " 패시브 ",
    target: " 적군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 중 매 턴 행동 시 14%→28%의 확률로 적군 전체에게 무기 피해 부여(피해율 53%→106%), 효력이 없으면 발동률 10% 증가 및 자신이 7회 일반 공격을 받은 후 1탄 동안 허약 상태(피해 줄기 불가) 획득 및 발동률 리셋. 자신이 주장이면 발동률 초기화 확률이 17.5%→35%까지 증가 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 대담무쌍 ",
    warLords: [" 조운 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 자신이 통찰 상태(모든 제어 효과 면역) 획득, 무력, 지력, 속도, 통솔, 20→40 증가. 자신이 주장일 때 25→50 증가 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 뛰어난 사슬 ",
    warLords: [" 태사자 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 자신이 연격 상태를 획득하여 턴마다 2회 일반 공격을 가하고 목표의 통솔 5→25 감소, 중첩 가능, 2탄 지속",
  },
  {
    rank: "S ",
    skillName: " 문무 겸비 ",
    warLords: [" 종회", "등애 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 자신이 책략 피해를 줄 때마다 지력 15→30 증가, 최대 5회 중첩 가능. 무기 피해를 줄 때마다 무력 15→30 증가, 최대 5회 중첩 가능",
  },
  {
    rank: "S ",
    skillName: " 병무상세 ",
    warLords: [" 축융부인", " 전풍 "],
    type: " 패시브 ",
    target: " 단일 적군 ",
    percentage: " 100% ",
    desc: " 전투 중 일반 공격 누적 3회 시 공격 목표에게 책략 피해(피해율 120%→240%, 지력의 영향) 및 자신을 치료(치료율 90%→ 180%, 지력의 영향)",
  },
  {
    rank: "S ",
    skillName: " 사별삼일 ",
    warLords: [" 여몽 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 시작 후 3번째 턴까지 일반 공격 불가, 15→30%의 확률로 모면효과 획득, 4번째 턴에 자신의 지력 34→68 상승 및 적군 전체에게 책략 피해 부여(피해율 90→180%, 지력의 영향) ",
  },
  {
    rank: "S ",
    skillName: " 신화계 ",
    warLords: [" 주유 "],
    type: " 패시브 ",
    target: " 적군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 중 액티브 전법을 발동할 때마다 40%→80%의 확률로 적군 전체에게 책략 공격(피해율 34%→68%, 지력의 영향). 자신이 주장일 때 해당 공격이 20%→40%의 확률로 목표에게 연소 상태 부여(피해율 34%, 지력의 영향), 1턴 지속 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 연인의 포효 ",
    warLords: [" 장비 "],
    type: " 패시브 ",
    target: " 적군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후 2,4번째 턴에 적군 전체에게 무기 공격(피해율 52%→104%), 목표가 무장 해제 상태이면 추가로 목표의 통솔 25%→50% 감소, 2턴 지속. 자신이 주장일 때 통솔 감소 효과가 허망 상태의 목표에게도 추가 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 유혹 ",
    warLords: [" 대교", "견희 "],
    type: " 패시브 ",
    target: " 단일 적군 ",
    percentage: " 100% ",
    desc: " 자신이 일반 공격을 받을 때 20%→40%의 확률로 공격자에게 혼란(전법과 관계없이 목표 선택해 공격), 허망(액티브 전법 발동 불가), 무장 해제(일반 공격 불가),허약(피해 주기 불가)상태 중 1개 부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 장구직입 ",
    warLords: [" 서황 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 무기 피해를 줄 때마다 자신이 주는 무기 피해7.5%→15% 증가, 최대5회 중첩 가능",
  },
  {
    rank: "S ",
    skillName: " 절대반격 ",
    warLords: [" 하후돈", "여령기 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " (기병,방패병,창병 전용)전투 중 자신이 무기 피해를 받을 때마다 무력 3→6 증가, 최대 10회 중첩 가능. 5번 째 턴의 중첩 횟수에 따라 적군 전체에게 무기 피해 부여(피해율 60%→120%, 매번 피해율 7%→14% 증가)",
  },
  {
    rank: "S ",
    skillName: " 주지육림 ",
    warLords: [" 동탁 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 턴마다 자신의 병력 감소(1%X턴 수), 또한 턴마다 배반(무기 피해를 줄 때 자신의 피해량을 기준으로 일정한 병력 회복) 4%→8% 및 무력 15 회복. 자신이 주장이면 5번째 턴부터 아군 부장이 살아있으면 턴마다 적군과 아군 전체에게 무기 피해(피해율30%→60%) ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 통렬한 자중 ",
    warLords: [" 정보 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 피해를 받을 때 20%→35% 확률로 자신의 디버프를 정화하며, 랜덤 단일 적군 대상이 공포 상태에 들어가게 하고(이동 불가), 1턴이 지속됩니다. 이 효과는 매 턴에 최대 한 번을 촉발할 수 있습니다. ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 호치 ",
    warLords: [" 허저 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 턴마다 단일 적군 대상을 선택하여 피해 고정 및 대상에게 주는 피해 16.5%→33% 증가, 목표를 격파하면 전투가 끝날 때까지 자신이 적진 격파 상태 획득(피해를 줄 때 목표의 통솔과 지력 무시)",
  },
  {
    rank: "S ",
    skillName: " 흩뿌려진 피 ",
    warLords: [" 마초 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 자신의 무력 17→34 및 범위 공격(일반 공격 시 목표와 같은 부대의 다른 장수에게 피해 부여)효과 27%→54% 획득. 자신이 주장이면 범위 공격치 30%→60% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 병력 소집 ",
    warLords: [" 서황", "원소 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 자신이 휴식 상태를 획득하여 턴마다 일정 병력 회복(회복률 62%→124%)",
  },
  {
    rank: "S ",
    skillName: " 봉시진 ",
    warLords: [" 황월영", "악진 "],
    type: " 진법 ",
    target: " 아군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 중 아군 주장이 주는 피해와 책략 피해 15%→30% 증가, 받는 무기 피해와 책략 피해 20% 증가. 아군 부장이 주는 무기 피해와 책략 피해 15% 감소, 받는 무기 피해와 책략 피해 12.5%→25% 감소",
  },
  {
    rank: "S ",
    skillName: " 팔문금쇄진 ",
    warLords: [" 조인 "],
    type: " 진법 ",
    target: " 적군 다수(2명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후 3번째 턴까지 적군 다수 대상(2명)이 주는 피해 15%→30% 감소(지력의 영향) 및 아군 주장이 선공 효과(우선 행동) 획득",
  },
  {
    rank: "S ",
    skillName: " 고지악래 ",
    warLords: [" 전위 "],
    type: " 지휘 ",
    target: " 아군 주장 ",
    percentage: " 100% ",
    desc: " 아군 주장이 일반 공격을 받을 때 자신이 공격자에게 맹격 1회 시전(피해율 40%→80%), 주는 무기 피해 9%→18% 감소, 1턴 지속, 그 후 아군 주장의 일반 공격 분담",
  },
  {
    rank: "S ",
    skillName: " 공신 ",
    warLords: [" 황월영 "],
    type: " 지휘 ",
    target: " 아군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후 3번째 턴까지 아군 전체가 선공 상태(우선 행동)획득, 아군 주장이 주는 피해 15%→30% 증가, 아군 부장이 주는 피해 7.5%→15% 증가. 4번째 턴부터 아군 전체가 주는 피해 15% 감소, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 금단의 비술 ",
    warLords: [" 좌자 "],
    type: " 지휘 ",
    target: " 아군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후 2번째 턴까지 아군 전체가 모면 효과를17.5%→35% 획득하여 피해 면역, 3번째 턴부터 휴식 상태 획득(턴마다 병력 1회 회복, 회복률 29%→58%, 지력의 영향), 3턴 지속",
  },
  {
    rank: "S ",
    skillName: " 기세등등 ",
    warLords: [" 안량", "조비 "],
    type: " 지휘 ",
    target: " 적군 다수(2명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후 2번째 턴까지 적군 다수 대상(2명)에게 턴마다 45%→90%의 확률로 무장 해제 상태 부여, 대상 일반 공격 불가",
  },
  {
    rank: "S ",
    skillName: " 꺽인 기세 ",
    warLords: [" 손견", " 진군 "],
    type: " 지휘 ",
    target: " 단일 적군 ",
    percentage: " 100% ",
    desc: " 전투 시작 후 3번째 턴까지 단일 적군 대상에게 허약 상태 부여, 피해를 줄 때 32.5%→65%의 확률로 피해 부여 불가",
  },
  {
    rank: "S ",
    skillName: " 꿈 속의 처단 ",
    warLords: [" 조조 "],
    type: " 지휘 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 시작 후 2번째 턴까지 자신이 주장이면 랜덤의 부장이 자신의 피해 20%→40% 분담, 3번째 턴부터 자신이 행동 시 디버프가 있으면 25%→50% 확률로 전투 종료 때까지 반격 상태 획득(피해율 150%) ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 난세의 간웅 ",
    warLords: [" 조조 "],
    type: " 지휘 ",
    target: " 아군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 중 우군 다수 대상(2명)이 주는 피해 8%→16% 증가(지력의 영향), 자신이 받는 피해 9%→18% 감소(지력의 영향). 자신이 주장이면 부장이 피해를 줄 때 해당 피해량의 10% 만큼 병력 회복 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 대설전 ",
    warLords: [" 제갈량 "],
    type: " 지휘 ",
    target: " 적군 다수(3명) ",
    percentage: " 100% ",
    desc: " 적군이 액티브 전법 발동 시 15%→25%의 확률로 해당 적군의 발동률 5%감소(지력의 영향 )및 자신과 랜덤 우군의 액티브 전법 발동률 2%→4% 증가(지력의 영향), 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 백의 도강 ",
    warLords: [" 여몽 "],
    type: " 지휘 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 시작 후 첫 번째 턴에 아군 전체가 방어 1회 획득.자신이 무기 공격 시 20%→40%의 확률로 단일 적군 대상에게 무장 해제(일반 공격 불가)부여, 2턴 지속.책략 피해를 줄 때 20%→40%의 확률로 단일 적군 대상에게 허망(액티브 전법 발동 불가) 부여, 1턴 지속, 해당 효과는 턴마다 각각 최대1회 발동 가능",
  },
  {
    rank: "S ",
    skillName: " 세상에 가득찬 덕 ",
    warLords: [" 유비 "],
    type: " 지휘 ",
    target: " 아군 다수(2명) ",
    percentage: " 100% ",
    desc: " 턴마다 아군 다수를 치료(2명, 치료율 34%→68%, 지력의 영향)하고 5%→10%의 확률로 적군 단일 대상에게 허약 상태(피해 주기 불가)부여, 1턴 지속. 자신이 주장이면 허약 상태의 부여 확률이 12.5%→25%까지 증가 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 수이필고 ",
    warLords: [" 정욱", "조식 "],
    type: " 지휘 ",
    target: " 적군 주장 ",
    percentage: " 100% ",
    desc: " 전투 시작 시 적군 주장을 도발하고(목표가 자신을 일반 공격) 자신의 통솔 20→40 증가, 4턴 지속",
  },
  {
    rank: "S ",
    skillName: " 신기묘산 ",
    warLords: [" 제갈량 "],
    type: " 지휘 ",
    target: " 적군 다수(2명) ",
    percentage: " 100% ",
    desc: " 적군 다수 대상(2명)이 액티브 전법 발동 시 25%→35%의 확률로 패배 및 대상에게 책략 피해 부여(피해율100%, 지력의 영향). 자신이 주장이면 해당 피해가 양측의 지력의 차에 따라 추가로 증가 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 신묘한 술법 ",
    warLords: [" 우길 "],
    type: " 지휘 ",
    target: " 적군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후 2번째 턴부터 적군 전체에게 수공 상태 부여, 턴마다 지속 피해(피해율36%→72%, 지력의 영향), 5턴 지속",
  },
  {
    rank: "S ",
    skillName: " 십승실패 ",
    warLords: [" 곽가 "],
    type: " 지휘 ",
    target: " 우군 주장 ",
    percentage: " 100% ",
    desc: " 전투 시작 후 2번째 턴까지 아군 주장이 통찰상태(모든 제어 효과에 면역)획득, 받는 피해 25%→50% 감소",
  },
  {
    rank: "S ",
    skillName: " 의심소열 ",
    warLords: [" 유비 "],
    type: " 지휘 ",
    target: " 아군 다수(3명) ",
    percentage: " 100% ",
    desc: " 전투 중 자신이 치료 효과를 부여할 때 목표가 받는 액티브 전법 피해가 7%→14%(지력의 영향) 감소, 1턴 지속. 자신의 병력이 처음으로 30%→40% 미만일 때 아군 전체가 피해를 받으면 25%→50% 분담, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 잠피기봉 ",
    warLords: [" 방덕", "서서 "],
    type: " 지휘 ",
    target: " 아군 다수(2명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후 3번째 턴까지 아군 중 지력이 가장 높은 장수가 받는 무기 피해 20%→40% 감소(지력의 영향),아군 중 무력이 가장 높은 장수가 받는 책략 피해 20%→40% 감소(지력의 영향)",
  },
  {
    rank: "S ",
    skillName: " 좌단동남 ",
    warLords: [" 손권 "],
    type: " 지휘 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 전투 중 자신과 우군의 단일 대상이 일반 공격을 발동하면 자신이 37.5%→75%의 확률로 연격, 통찰, 선공, 필중, 적진 격파 상태 중 1개를 랜덤 획득, 2턴 지속.자신이 주장이면 우선적으로 다른 상태 획득 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 청낭 ",
    warLords: [" 화타 "],
    type: " 지휘 ",
    target: " 아군 다수(2명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후4번째 턴까지 아군 다수 대상(2명)이 통솔20→40(지력의 영향)과 구급 효과 획득,매회 피해를 받을 때50%확률로 일정한 병력 회복(치료율44%→88%,지력의 영향)",
  },
  {
    rank: "S ",
    skillName: " 화신의 기개 ",
    warLords: [" 축융 부인 "],
    type: " 지휘 ",
    target: " 아군 다수(2명) ",
    percentage: " 100% ",
    desc: " 전투 시작 후2번째 턴까지 아군 다수 대상(2명)이 필중 상태 획득, 3번째 턴에 허약 상태(피해 주기 불가)면역 및 자신의 매 턴 행동 전에 아군 다수대상 치료(2명,치료율 79%→158%,무력의 영향), 3턴 지속",
  },
  {
    rank: "S ",
    skillName: " 강동맹호 ",
    warLords: [" 손견 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 50% ",
    desc: " 적군 다수 대상(2명)에게 무기 피해 63%→126% 및 도발(목표가 자신을 일반 공격), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 경국의 미인 ",
    warLords: [" 초선 "],
    type: " 액티브 ",
    target: " 적군 다수(1~2명) ",
    percentage: " 25%→40% ",
    desc: " 1턴 준비 후 적군 다수 대상(1~2명)에게 혼란 상태 부여(전법과 관계없이 목표 선택해 공격) 및 50%의 확률로 아군 다수 대상(2명)이 받는 피해 8%→16% 감소, 2턴 지속, 자신이 여성이면 반드시 적군의 다수 대상(2명)선택 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 고육계 ",
    warLords: [" 황개 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 40% ",
    desc: " 자신에게 무기 피해를 주고(피해율40%) 단일 적군 대상에게 연소(피해율 61%→122%, 지력의 영향)와 혼란(전법과 관계없이 목표를 선택해 공격)상태 부여 및 자신이 받는 무기 피해 15%→30% 감소, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 관우의 상처 ",
    warLords: [" 화타 "],
    type: " 액티브 ",
    target: " 단일 아군 ",
    percentage: " 40% ",
    desc: " 병력 손실이 가장 많은 단일 아군 대상의 디버프 해제 및 병력 회복(치료율128%→256%, 지력의 영향)",
  },
  {
    rank: "S ",
    skillName: " 굳건한 군대 ",
    warLords: [" 우금 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 35% ",
    desc: " 자신이 다음에 받는 무기 피해가 40%증가, 1턴 지속.자신의 무력 28→56 증가, 3턴 지속. 또한 적군 다수 대상(2명)에게 맹렬한 일격 발동(피해율 92%→184%)",
  },
  {
    rank: "S ",
    skillName: " 굳건한 마음 ",
    warLords: [" 서서 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 35% ",
    desc: " 적군 다수 대상(2명)이 30%→60%의 확률로 연소(지력의 영향), 중독(지력의 영향), 패배(무력의 영향)상태 랜덤 획득, 턴마다 지속 피해(피해율70%), 상태마다 독립 판정, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 깔끔한 계책 ",
    warLords: [" 종회 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 45% ",
    desc: " 1턴 준비 후 적군 2명에게 책략 공격(피해율 105%→210%, 지력의 영향) 및 무장 해제(일반 공격 불가), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 난공불락 ",
    warLords: [" 조인 "],
    type: " 액티브 ",
    target: " 자신 ",
    percentage: " 35%→45% ",
    desc: " 자신이 통찰 상태(모든 제어 효과 면역)획득 및 적군 전체 도발(목표가 자신에게 일반 공격), 또한 자신의 통솔 75→150 증가, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 대륙의 위세 ",
    warLords: [" 관우 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 35% ",
    desc: " 1턴 준비 후 적군 전체에게 맹공(피해율 73%→146%)및 대상에게 랜덤으로 무장 해제(일반 공격 불가) 또는 허망(액티브 전법 발동 불가) 부여, 1턴 지속. 자신이 주장일 때 추가로 자신이 주는 무기 피해 18%→36% 증가, 2턴 지속 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 독주 ",
    warLords: [" 이유 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 70% ",
    desc: " 단일 적군 대상에게 독주를 시전하여 대상의 무력 30%→60% 감소(지력의 영향), 1턴 지속, 1턴 후 독이 퍼져 책략 공격 발동(피해율113%→226%, 지력의 영향)및 대상의 통솔 30→60 감소(지력의 영향), 전투 종료까지 무제한 중첩 가능",
  },
  {
    rank: "S ",
    skillName: " 맹렬한 불길 ",
    warLords: [" 육손 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 35% ",
    desc: " 1턴 준비 후 적군 전체에게 화공(피해율 51%→102%,지력의 영향)및 연소 상태 부여, 턴마다 지속 피해(피해율 36%→72%, 지력의 영향), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 목숨 건 전투 ",
    warLords: [" 방덕 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 30% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)의 버프를 해제하고 무기 공격(피해율 127.5%→255%)",
  },
  {
    rank: "S ",
    skillName: " 무한한 충성 ",
    warLords: [" 전풍 "],
    type: " 액티브 ",
    target: " 적군 다수(1~2명) ",
    percentage: " 35%→50% ",
    desc: " 1턴 준비 후 적군 다수 대상(1~2명)의 속도 15% 감소(지력의 영향) 및 혼란 상태(전법과 관계없이 목표 선택해 공격)부여, 2턴 지속. 또한 우군 단일 대상이 방어 1회 획득, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 백발 백중 ",
    warLords: [" 황충 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 35% ",
    desc: " 1턴 준비 후 자신의 회심 확률 12.5%→25% 증가(발동 시 무기 피해 100%증가), 2턴 지속. 이후 적군 전체에게 무기 공격(피해율 90%→180%), 목표가 제어 상태일 경우 이번 무기 공격 더욱 강화(피해율 120%→240%)",
  },
  {
    rank: "S ",
    skillName: " 병봉 ",
    warLords: [" 장소", "맹획 "],
    type: " 액티브 ",
    target: " 아군 다수(2명) ",
    percentage: " 25%→35% ",
    desc: " 자신과 우군 단일 대상이 연격(턴마다 일반 공격2회 가능)상태 획득, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 분노한 창 ",
    warLords: [" 장비 "],
    type: " 액티브 ",
    target: " 자신 ",
    percentage: " 40% ",
    desc: " (기병,방패병,창병,병기 전용)자신이 무력 25→50 증가 및 범위 공격(일반 공격 시 목표와 같은 부대의 다른 장수에게 피해 부여) 획득(피해율 35%→70%), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 불난 데 부채질 ",
    warLords: [" 주유", "황개 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 45% ",
    desc: " 단일 적군 대상에게 책략 피해(피해율 77%→154%, 지력의 영향), 목표가 연소 상태이면 추가로 책략 피해 1회(피해율 99%→198%, 지력의 영향)",
  },
  {
    rank: "S ",
    skillName: " 사면초가 ",
    warLords: [" 순욱", "이유 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 50% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 중독 상태를 시전하여 턴마다 지속 피해(피해율 72%→144%, 지력의 영향), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 사자분신 ",
    warLords: [" 여령기 "],
    type: " 액티브 ",
    target: " 적군 다수(2~3명) ",
    percentage: " 35% ",
    desc: " 단일 적군 대상 및 추가로 적군 1~2명에게 무기 공격(피해율 59%→118%), 자신의 액티브 전법 발동률 5%→10% 증가(자신이 주장일 때 발동률 7.5%→15%까지 증가), 2턴 지속, 단일 대상의 목표가 적군 주장이면 대산에게 모반 상태 부여, 턴마다 지속 피해(피해율 51%→102%, 무력 또는 지력 중 높은 항목의 영향을 받고 방어 무시), 2턴 지속 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 십면매복 ",
    warLords: [" 정욱 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 35% ",
    desc: " 디버프 상태의 적군에게 책략 공격(피해율 48%→ 96%, 지력의 영향) 후, 적군 다수 대상(2명)에게 치료 금지(병력 회복 불가) 및 모반 상태를 부여하여 턴마다 지속 피해(피해율 37%→74%, 무력 또는 지력 중 높은 항목의 영향을 받고 방어 무시), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 양동작전 ",
    warLords: [" 등애 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 25%→50% ",
    desc: " 1턴 준비 후 단일 적군 대상에게 책략 공격(피해율260%, 지력의 영향) 및 공포 상태(행동 불가) 부여, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 와신상담 ",
    warLords: [" 손권 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 45% ",
    desc: " 적군 다수 대상(2명)에게 무기 공격 1회(피해율 48%→96%) 및 25%의 확률로(자신의 연격, 통찰, 선공, 필증, 적진 격파 상태가 1개 증가할 때마다 확률 5%→10% 증가)공포 상태(행동 불가) 부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 용감무쌍 ",
    warLords: [" 문추 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 55% ",
    desc: " 단일 대상 목표에게 무기 공격(피해율 104%→208%) 및 무장 해제(일반 공격 불가), 자신의 통솔 40%감소 및 치료 금지 상태(병력 회복 불가) 부여, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 유인책 ",
    warLords: [" 사마휘", "화웅 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 40% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 모래폭풍 상태 부여, 턴마다 지속 피해(피해율 63%→126%, 지력의 영향) 및 대상이 받는 무기 피해 25%증가, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 의심암귀 ",
    warLords: [" 좌자", "우길 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 50% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 책략 공격 1회(피해율 76.5%→153%) 및 아군 다수 대상(2명)의 일정한 병력 회복(회복률 51%→102%, 지력의 영향)",
  },
  {
    rank: "S ",
    skillName: " 이어지는 명성 ",
    warLords: [" 원소 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 50% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 무기 공격 1회(피해율 63%→126%), 대상의 통솔 12→24 감소(무력의 영향) 및 연소 상태를 부여하여 턴마다 지속 피해(피해율30%→60%, 지력의 영향), 2턴 지속. 자신이 주장이면 추가로 아군 전체의 통솔 40→80% 증가, 3턴 지속 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 이일대로 ",
    warLords: [" 법정 "],
    type: " 액티브 ",
    target: " 아군 다수(2명) ",
    percentage: " 35% ",
    desc: " 아군 다수 대상 치료(2명, 치료율77%→154%, 지력의 영향) 및 다음 3회 피해에서 받는 피해 감소(각각25%→50%, 18.8%→37.5%, 12.5%→25%), 지력의 영향) 다음 제어 상태에 25%→40%의 확률(지력의 영향)로 면역",
  },
  {
    rank: "S ",
    skillName: " 일망타진 ",
    warLords: [" 관우", "조운 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 40% ",
    desc: " 적군 전체에게 무기 피해 50%→100% 부여, 목표가 무장 해제 또는 허망 상태이면 20%→30%의 확률로 목표에게 공포 상태(행동 불가)부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 일망타진 ",
    warLords: [" 관우", "조운 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 40% ",
    desc: " 적군 전체에게 무기 피해 50%→100% 부여, 목표가 무장 해제 또는 허망 상태이면 20%→30%의 확률로 목표에게 공포 상태(행동 불가)부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 일제 사격 ",
    warLords: [" 황충", "하후연 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 40% ",
    desc: " (궁병 전용) 1턴 준비 후 적군 전체에게 무기 공격 발동(피해율 70%→140%) 및 50%의 확률로 패배 상태를 부여하여 턴마다 지속 피해(피해율 60%→120%, 무력의 영향), 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 임전선동 ",
    warLords: [" 악진 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 100% ",
    desc: " 적군 다수 대상(2명)에게 무기 공격(피해율 67.5%→135%) 후 자신에게 허약 상태(피해 주기 불가) 부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 적진 함락 ",
    warLords: [" 손책", "문추 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 35% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)의 통솔, 지력 40→80 감소(무력의 영향), 2턴 지속 및 대상에게 무기 공격 1회(피해율79%→158%)",
  },
  {
    rank: "S ",
    skillName: " 천하무쌍 ",
    warLords: [" 여포 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 25%→35% ",
    desc: " 단일 적군 대상에게 결투를 요청하여 양측이 순서대로 상대방에게 일반공격 3회 가함, 자신이 우선 공격 진행. 결투 중 양측은 무장 해제와 공포 상태에 영향을 받지 않고 범위 공격과 돌격 전법 발동 가능. 자신이 주장이면 결투 후 자신이 받는 무기 피해 3.5%→7% 감소(무력의 영향), 2턴 지속 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 천하무적 ",
    warLords: [" 마초", "허저 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 30% ",
    desc: " (기병,방패병,창병,병기 전용) 1턴 준비 후 적군 전체에게 무기 공격 1회(피해율 102.4%→204.8%)",
  },
  {
    rank: "S ",
    skillName: " 청천벽력 ",
    warLords: [" 장각 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 45% ",
    desc: " 1턴 준비 후 적군 랜덤 단일 대상에게 책략 공격(피해율 51%→102%, 지력의 영향), 총5회 발동하며 매번 별도로 목표 선택. 목표가 수공상태이면 30%확률로 공토 상태 부여(행동 불가), 1턴 지속. 자신이 주장이면 공포의 확률 50%증가 및 모래폭풍 상태에 유효 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 침사결수 ",
    warLords: [" 곽가", "법정 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 40% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 수공 상태 부여,턴마다 지속 피해(피해율 63%→126%,지력의 영향을 받음) 및 대상이 받는 책략 피해 25%증가, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 폐월 ",
    warLords: [" 초선 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 40%→75% ",
    desc: " 적군 1명을 선택하여 자신의 피해 12.5%→25% 분담(지력의 영향). 목표가 적군 중 무력이 가장 높으면 혼란 상태 부여(전법과 관계없이 목표 선택해 공격), 목표가 적군 중 지력이 가장 높으면 허망 상태 부여(액티브 전법 발동 불가) 또는 허약(피해 주기 불가)과 치료 금지(병력 회복 불가)상태 부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 호가의 소리 ",
    warLords: [" 채문희 "],
    type: " 액티브 ",
    target: " 아군 다수(2명) ",
    percentage: " 50% ",
    desc: " 아군 다수 대상 치료(2명, 치료율 61%→122%, 지력의 영향) 및 자신과 우군의 단일 대상이 받는 피해 13%→26% 감소(지력의 영향), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 호전적 군웅 ",
    warLords: [" 화웅 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 35% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 무기 공격 1회(피해율 100%→200%), 이후 자신이 주는 무기 피해12.5%→25% 증가, 받는 무기 피해 감소(12.5%→25%, 무력의 영향), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 혼비백산 ",
    warLords: [" 소교", " 채문희 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 55% ",
    desc: " 단일 적군 대상의 무력, 지력, 속도, 통솔 19→38 훔치기(지력의 영향을 받음), 2턴 지속, 2회 중첩 가능",
  },
  {
    rank: "S ",
    skillName: " 화소연영 ",
    warLords: [" 육손 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 50% ",
    desc: " 단일 적군 대상에게 연소 상태(피해율 41%→82%, 지력의 영향) 부여, 3턴 지속, 랜덤으로 2회 부여. 만약 이미 연소 상태의 목표일 경우 적군 전체에 책략 공격(31%→62%, 지력의 영향, 자신을 주장으로 할 때, 피해율이 49%→98%까지 증가), 또한 30% 확률로 연소 상태의 적군에 위협 상태 부여, 1턴 지속, 이후 또다른 적군에게 연소 상태 부여 ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 황천태평 ",
    warLords: [" 장각 "],
    type: " 액티브 ",
    target: " 적군 다수 ",
    percentage: " (2명) ",
    desc: " 25%→35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 대극사 ",
    warLords: [" 장합 "],
    type: " 장합 ",
    target: " 병종 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 등갑병 ",
    warLords: [" 올돌골 "],
    type: " 올돌골 ",
    target: " 병종 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 무당비군 ",
    warLords: [" 왕평 "],
    type: " 왕평 ",
    target: " 병종 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 백마의종 ",
    warLords: [" 공손찬 "],
    type: " 공손찬 ",
    target: " 병종 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 백이병 ",
    warLords: [" 진도 "],
    type: " 진도 ",
    target: " 병종 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 서량의 철기 ",
    warLords: [" 마등 "],
    type: " 마등 ",
    target: " 병종 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 함진영 ",
    warLords: [" 고순 "],
    type: " 고순 ",
    target: " 병종 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 호표기 ",
    warLords: [" 조순 "],
    type: " 조순 ",
    target: " 병종 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 극악무도 ",
    warLords: [" 동탁 "],
    type: " 돌격 ",
    target: " 단일 적군 ",
    percentage: " 25%→35% ",
    desc: " 일반 공격 후 공격 목표에게 추가로 무기 공격 1회(피해율 196%) 및 혼란 상태(전법과 관계없이 목표 선택해 공격) 부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 극적제승 ",
    warLords: [" 정보", "우금 "],
    type: " 돌격 ",
    target: " 단일 적군 ",
    percentage: " 40% ",
    desc: " 일반 공격 후 공격 목표에게 추가로 책략 피해 1회(피해율 90%→180%, 지력의 영향), 목표가 패배나 중독 상태이면 70%의 확률로 목표에게 허약 상태(피해 주기 불가)부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 삼군의 으뜸 ",
    warLords: [" 안량 "],
    type: " 돌격 ",
    target: " 단일 적군 ",
    percentage: " 30% ",
    desc: " 일반 공격 후 공격 목표에게 추가로 맹공(피해율 90%→180%)및 공포 상태(행동 불가) 부여, 1턴 지속",
  },
  {
    rank: "S ",
    skillName: " 일기당천 ",
    warLords: [" 여포 "],
    type: " 돌격 ",
    target: " 적군 다수(3명) ",
    percentage: " 30% ",
    desc: " 일반 공격 후 적군 전체에게 무기 공격1회(피해율 36%→72%). 자신이 주장이면 해당 무기 공격이 더욱 강력하게 변화(피해 율54%→108%) ",
    hasCaptainImpact: true,
  },
  {
    rank: "S ",
    skillName: " 장수의 속도 ",
    warLords: [" 하후연 "],
    type: " 돌격 ",
    target: " 단일 적군 ",
    percentage: " 30%→60% ",
    desc: " 일반 공격 후 랜덤의 단일 적군 대상에게 무기 공격 1회(피해율 158%), 적군 주장을 명중시키면 허망 상태 부여 가능(액티브 전법 발동 불가), 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 적군 제압 ",
    warLords: [" 태사자", "전위 "],
    type: " 돌격 ",
    target: " 단일 적군 ",
    percentage: " 25%→45% ",
    desc: " 일반공격 후 랜덤 단일 적군 대상의 통솔과 지력 100감소, 2턴 지속. 자신이 주장이 아니면 추가로 아군 주장이 방어 2회 획득, 피해 면역 가능, 2턴 지속",
  },
  {
    rank: "S ",
    skillName: " 적진 습격 ",
    warLords: [" 감녕 "],
    type: " 돌격 ",
    target: " 단일 적군 ",
    percentage: " 40% ",
    desc: " (기병 전용)일반 공격 후 랜덤의 단일 적군 대상에게 무기 공격 1회(피해율 81%→162%) 및 50%의 확률로 적군 주장에게 무기 공격 1회(피해율 60%→120%)",
  },
  {
    rank: "S ",
    skillName: " 공훈 거사 ",
    warLords: [" 장소 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 주정관으로 임명하면 전체 자원의 생산량 1.3%→2.5% 증가",
  },
  {
    rank: "S ",
    skillName: " 고고한 명성 ",
    warLords: [" 진군 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 제철관으로 임명하면 철광 생산량 1.5%→3% 증가",
  },
  {
    rank: "S ",
    skillName: " 나라의 발전 ",
    warLords: [" 조비 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 주정관을 임명하면 건물 레벨업 시간 15%→30% 감소",
  },
  {
    rank: "S ",
    skillName: " 수경 선생 ",
    warLords: [" 사마휘 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 탐방사로 임명하면 고급 보상을 찾을 확률 4.5%증가",
  },
  {
    rank: "S ",
    skillName: " 왕좌지재 ",
    warLords: [" 순욱 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수의 정치 36→72 증가",
  },
  {
    rank: "S ",
    skillName: " 절세 미인 ",
    warLords: [" 대교 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 무역관으로 임명하면 무역비율 1.5%→3% 증가",
  },
  {
    rank: "S ",
    skillName: " 칠보성시 ",
    warLords: [" 조식 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 단조관으로 임명하면 고급 장비 단조 확률 4.5%→9% 증가",
  },
  {
    rank: "S ",
    skillName: " 타고난 미모 ",
    warLords: [" 소교 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수의 매력 13.5%→27% 증가",
  },
  {
    rank: "S ",
    skillName: " 화용월태 ",
    warLords: [" 견희 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 훈련사로 임명하면 훈련경험치 획득 3%→6% 증가",
  },
  {
    rank: "A ",
    skillName: " 굳센 의지 ",
    warLords: [" 주창 "],
    type: " 주창 ",
    target: " 패시브 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 백동성강 ",
    warLords: [" 여범", "서성 "],
    type: " 패시브 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 자신의 무력, 지력, 통솔, 속도 18→36 증가",
  },
  {
    rank: "A ",
    skillName: " 백미 ",
    warLords: [" 마량 "],
    type: " 마량 ",
    target: " 패시브 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 분투 ",
    warLords: [" 관평 "],
    type: " 관평 ",
    target: " 패시브 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 자가 치유 ",
    warLords: [" 동습 "],
    type: " 동습 ",
    target: " 패시브 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 침착한 대응 ",
    warLords: [" 황보숭 "],
    type: " 황보숭 ",
    target: " 패시브 ",
    percentage: " 단일 적군 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 거짓 항복 ",
    warLords: [" 요화 "],
    type: " 요화 ",
    target: " 지휘 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 대항의 자벽 ",
    warLords: [" 곽회 "],
    type: " 곽회 ",
    target: " 지휘 ",
    percentage: " 아군 다수(2명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 장자의 바람 ",
    warLords: [" 이만성 "],
    type: " 이만성 ",
    target: " 지휘 ",
    percentage: " 아군 다수(3명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 진퇴양난 ",
    warLords: [" 유봉 "],
    type: " 유봉 ",
    target: " 지휘 ",
    percentage: " 적군 다수(2명) ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 황건적 평정 ",
    warLords: [" 주준 "],
    type: " 지휘 ",
    target: " 양측 전체 ",
    percentage: " 100% ",
    desc: " 전투 시작 후 2번째 턴에 아군 전체에게 모래폭풍 면역 상태 부여, 적군 전체는 모반 상태가 되어 턴마다 지속 피해(피해율 44%→88%, 무력 또는 지력 중 높은 항목의 영향을 받고 방어 무시), 2턴 지속, 목표가 황건군이면 피해율 20% 증가",
  },
  {
    rank: "A ",
    skillName: " 가혹한 세금 ",
    warLords: [" 곽사 "],
    type: " 곽사 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 45% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 강공 ",
    warLords: [" 간옹", "기령 "],
    type: " 액티브 ",
    target: " 액티브 ",
    percentage: " 25%→45% ",
    desc: " 자신에게 연격 상태 부여(턴마다 일반 공격 2회 가능), 1턴 지속",
  },
  {
    rank: "A ",
    skillName: " 겁쟁이 ",
    warLords: [" 종요", "봉기 "],
    type: " 액티브 ",
    target: " 적군 다수 ",
    percentage: " 45% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 책략 공격(피해율 52.5%→105%, 지력의 영향)과 모래폭풍 상태 부여, 턴마다 지속 피해(피해율 60%→120%, 지력의 영향), 1턴 지속",
  },
  {
    rank: "A ",
    skillName: " 격렬한 설전 ",
    warLords: [" 왕랑 "],
    type: " 왕랑 ",
    target: " 액티브 ",
    percentage: " 적군 다수(3명) ",
    desc: " 50% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 겸양 ",
    warLords: [" 공융 "],
    type: " 공융 ",
    target: " 액티브 ",
    percentage: " 단일 아군 ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 고성사수 ",
    warLords: [" 심배 "],
    type: " 심배 ",
    target: " 액티브 ",
    percentage: " 아군 다수(2명) ",
    desc: " 45% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 낙뢰 ",
    warLords: [" 진림 "],
    type: " 액티브 ",
    target: " 기타 단일 ",
    percentage: " 50% ",
    desc: " 랜덤의 기타 단일 대상(5%의 확률로 우군에게 시전)에게 책략 공격(피해율 85%→170%, 지력의 영향)및 대상이 받는 책략 피해 9%→18% 증가, 2턴 지속",
  },
  {
    rank: "A ",
    skillName: " 낙봉 ",
    warLords: [" 장임 "],
    type: " 장임 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 뛰어난 기량 ",
    warLords: [" 마속 "],
    type: " 마속 ",
    target: " 액티브 ",
    percentage: " 아군 다수(2명) ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 무모 ",
    warLords: [" 관해 "],
    type: " 관해 ",
    target: " 액티브 ",
    percentage: " 자신 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 무차별 도륙 ",
    warLords: [" 조진 "],
    type: " 조진 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 백병전 ",
    warLords: [" 정봉 "],
    type: " 정봉 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  { rank: "A ", skillName: " 복배수적 ", warLords: [" 봉기"]},
  {
    rank: "A ",
    skillName: " 불벼락 ",
    warLords: [" 장흠 "],
    type: " 장흠 ",
    target: " 액티브 ",
    percentage: " 적군 다수(2명) ",
    desc: " 50% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 불의의 습격 ",
    warLords: [" 보연사 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 20%→35% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 랜덤으로 허망(액티브 전법 공격 불가)또는 무장 해제(일반 공격 불가)부여, 1~2턴 지속(30%의 확률로 2턴 지속)",
  },
  {
    rank: "A ",
    skillName: " 사명 완수 ",
    warLords: [" 반장 "],
    type: " 반장 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 성동격서 ",
    warLords: [" 동윤", "주준 "],
    type: " 액티브 ",
    target: " 적군 다수(2명) ",
    percentage: " 40% ",
    desc: " 1턴 준비 후 적군 다수 대상(2명)에게 책략 공격(피해율 87.5%→175%, 지력의 영향) 및 속도 15→30 감소, 2턴 지속",
  },
  {
    rank: "A ",
    skillName: " 세찬 동향 ",
    warLords: [" 장수 "],
    type: " 장수 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 신상사 ",
    warLords: [" 장만성 "],
    type: " 장만성 ",
    target: " 액티브 ",
    percentage: " 적군 다수(3명) ",
    desc: " 50% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 약점 간파 ",
    warLords: [" 장패 "],
    type: " 장패 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 50% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 여상의 상갑 ",
    warLords: [" 진무 "],
    type: " 진무 ",
    target: " 액티브 ",
    percentage: " 우군 단일 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 요술 ",
    warLords: [" 장보 "],
    type: " 장보 ",
    target: " 액티브 ",
    percentage: " 적군 다수(3명) ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 용감한 제비 ",
    warLords: [" 장연 "],
    type: " 장연 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 용맹한 행군 ",
    warLords: [" 호거아 "],
    type: " 호거아 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 45% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 위풍당당 ",
    warLords: [" 기령 "],
    type: " 액티브 ",
    target: " 적군 다수(1~2명) ",
    percentage: " 30%→45% ",
    desc: " 단일 적군 대상에게 도발(목표가 자신을 일반 공격) 또는 무장 해제(일반 공격 불가)상태 부여, 2턴 지속, 37.5%→75%의 확률로 추가 시전 1회",
  },
  {
    rank: "A ",
    skillName: " 의성 ",
    warLords: [" 서성 "],
    type: " 액티브 ",
    target: " 자신 ",
    percentage: " 75% ",
    desc: " 자신의 혼란상태 면역 및 무력 34→68 증가, 2턴 지속",
  },
  {
    rank: "A ",
    skillName: " 일격 섬멸 ",
    warLords: [" 장량 "],
    type: " 장량 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 전투의 귀재 ",
    warLords: [" 조홍 "],
    type: " 조홍 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 정화 ",
    warLords: [" 이엄 "],
    type: " 액티브 ",
    target: " 아군 다수 ",
    percentage: " 30%→45% ",
    desc: " 아군 다수 대상(2명)의 무력, 지력, 속도 12→24 증가, 2턴 지속 및 디버프 해제",
  },
  {
    rank: "A ",
    skillName: " 정확한 예측 ",
    warLords: [" 유엽 "],
    type: " 유엽 ",
    target: " 액티브 ",
    percentage: " 적군 다수(2명) ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 좌우개궁 ",
    warLords: [" 한당 "],
    type: " 한당 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 좌절의 습격 ",
    warLords: [" 조창 "],
    type: " 조창 ",
    target: " 액티브 ",
    percentage: " 적군 다수(2명) ",
    desc: " 25%→35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 진언 ",
    warLords: [" 곽도 "],
    type: " 곽도 ",
    target: " 액티브 ",
    percentage: " 우군 단일 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 천 리의 구원 ",
    warLords: [" 주환 "],
    type: " 주환 ",
    target: " 액티브 ",
    percentage: " 우군 다수(2명) ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 추방 ",
    warLords: [" 마철 "],
    type: " 액티브 ",
    target: " 적군 다수(3명) ",
    percentage: " 30%→45% ",
    desc: " 적군 전체의 버프 해제 및 자신의 지력 14→28 증가, 3턴 지속",
  },
  {
    rank: "A ",
    skillName: " 출병 약탈 ",
    warLords: [" 이각 "],
    type: " 이각 ",
    target: " 액티브 ",
    percentage: " 단일 적군 ",
    desc: " 35% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 화려한 기략 ",
    warLords: [" 황권 "],
    type: " 황권 ",
    target: " 액티브 ",
    percentage: " 적군 다수(2명) ",
    desc: " 45% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 휴전 ",
    warLords: [" 비의", "유표 "],
    type: " 액티브 ",
    target: " 단일 적군 ",
    percentage: " 40% ",
    desc: " 1턴 준비 후 아군 다수 대상(2명)의 책략 피해 12.5%→25% 증가, 1턴 지속. 이후 단일 적군 대상에게 책략 공격(피해율 105%→210%, 지력의 영향)",
  },
  {
    rank: "A ",
    skillName: " 날렵한 칼날 ",
    warLords: [" 문빙 "],
    type: " 문빙 ",
    target: " 돌격 ",
    percentage: " 단일 적군 ",
    desc: " 30% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 숨겨진 계책 ",
    warLords: [" 한수 "],
    type: " 한수 ",
    target: " 돌격 ",
    percentage: " 단일 적군 ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 용맹한 사수 ",
    warLords: [" 사마가 "],
    type: " 사마가 ",
    target: " 돌격 ",
    percentage: " 단일 적군 ",
    desc: " 40% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 고아한 정취 ",
    warLords: [" 이엄 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 목재관으로 임명하면 목재 생산량 1%→2% 증가",
  },
  {
    rank: "A ",
    skillName: " 고지식 ",
    warLords: [" 마철 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 조련관으로 임명하면 명마 생산 확률 2%→4% 증가",
  },
  {
    rank: "A ",
    skillName: " 군대 양성 ",
    warLords: [" 제갈근 "],
    type: " 제갈근 ",
    target: " 내정 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 뛰어난 언변 ",
    warLords: [" 양수 "],
    type: " 양수 ",
    target: " 내정 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 묘서명석 ",
    warLords: [" 간옹 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 채석관으로 임명하면 석재 생산량 1%→2% 증가",
  },
  {
    rank: "A ",
    skillName: " 밝은 통찰력 ",
    warLords: [" 여범 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수의 정치 12→24 증가",
  },
  {
    rank: "A ",
    skillName: " 빛나는 쇠조각 ",
    warLords: [" 종요 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 제철관으로 임명하면 철광 둔전의 수익 1.5%→3% 증가",
  },
  {
    rank: "A ",
    skillName: " 선견지명 ",
    warLords: [" 비의 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 무역관으로 임명하면 무역 비율 1%→2% 증가",
  },
  {
    rank: "A ",
    skillName: " 세심한 보필 ",
    warLords: [" 보연사 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 단조관으로 임명하면 단조 소모 2%→4% 감소",
  },
  {
    rank: "A ",
    skillName: " 시급한 사안 ",
    warLords: [" 유표 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 조련관으로 임명하면 조련 시간 5%→10% 감소",
  },
  {
    rank: "A ",
    skillName: " 임기응변 ",
    warLords: [" 미축 "],
    type: " 미축 ",
    target: " 내정 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 절차탁마 ",
    warLords: [" 동윤 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 제철관으로 임명하면 철광 생산량 1%→2% 증가",
  },
  {
    rank: "A ",
    skillName: " 절처봉생 ",
    warLords: [" 고옹 "],
    type: " 고옹 ",
    target: " 내정 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 조련의 장인 ",
    warLords: [" 장로 "],
    type: " 장로 ",
    target: " 내정 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
  {
    rank: "A ",
    skillName: " 주렁주렁 열매 ",
    warLords: [" 진림 "],
    type: " 내정 ",
    target: " 자신 ",
    percentage: " 100% ",
    desc: " 장수를 군량관으로 임명하면 식량 생산량 1%→2% 증가",
  },
  {
    rank: "A ",
    skillName: " 풍성한 오곡 ",
    warLords: [" 노식 "],
    type: " 노식 ",
    target: " 내정 ",
    percentage: " 자신 ",
    desc: " 100% ",
    hasCaptainImpact: true,
  },
];

