export const warlordData = [
  {
    rank: "S",
    skillName: "강동소패왕",
    warLords: ["손책"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투에서일반공격후35%의확률로목표에게추가로맹공(피해율96%→192%)발동및단일아군대상의병력회복(치료율28%→56%,무력의영향).자신이주장일때전투시작후2번째턴까지단일적군대상이처음받는피해15%→30%증가",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "강직한마음",
    warLords: ["하후돈"],
    type: "패시브",
    target: "적군다수(2명)",
    percentage: "100%",
    desc: "전투중자신의통솔19→38증가,무기피해를입으면40%의확률로적군다수대상(2명)에게무기피해(피해율42%→84%)",
  },
  {
    rank: "S",
    skillName: "금털의깃발",
    warLords: ["감녕"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중자신의회심확률25%→50%(발동시무기피해100%증가)및회심피해10%→20%증가.자신이주장일때우군다수대상(2명)의회심확률2.5%→5%와회심피해5%→10%증가",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "남만두목",
    warLords: ["맹획"],
    type: "패시브",
    target: "적군다수(3명)",
    percentage: "100%",
    desc: "전투중매턴행동시14%→28%의확률로적군전체에게무기피해부여(피해율53%→106%),효력이없으면발동률10%증가및자신이7회일반공격을받은후1탄동안허약상태(피해줄기불가)획득및발동률리셋.자신이주장이면발동률초기화확률이17.5%→35%까지증가",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "대담무쌍",
    warLords: ["조운"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중자신이통찰상태(모든제어효과면역)획득,무력,지력,속도,통솔,20→40증가.자신이주장일때25→50증가",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "뛰어난사슬",
    warLords: ["태사자"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중자신이연격상태를획득하여턴마다2회일반공격을가하고목표의통솔5→25감소,중첩가능,2탄지속",
  },
  {
    rank: "S",
    skillName: "문무겸비",
    warLords: ["종회", "등애"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중자신이책략피해를줄때마다지력15→30증가,최대5회중첩가능.무기피해를줄때마다무력15→30증가,최대5회중첩가능",
  },
  {
    rank: "S",
    skillName: "병무상세",
    warLords: ["축융부인", "전풍"],
    type: "패시브",
    target: "단일적군",
    percentage: "100%",
    desc: "전투중일반공격누적3회시공격목표에게책략피해(피해율120%→240%,지력의영향)및자신을치료(치료율90%→180%,지력의영향)",
  },
  {
    rank: "S",
    skillName: "사별삼일",
    warLords: ["여몽"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투시작후3번째턴까지일반공격불가,15→30%의확률로모면효과획득,4번째턴에자신의지력34→68상승및적군전체에게책략피해부여(피해율90→180%,지력의영향)",
  },
  {
    rank: "S",
    skillName: "신화계",
    warLords: ["주유"],
    type: "패시브",
    target: "적군다수(3명)",
    percentage: "100%",
    desc: "전투중액티브전법을발동할때마다40%→80%의확률로적군전체에게책략공격(피해율34%→68%,지력의영향).자신이주장일때해당공격이20%→40%의확률로목표에게연소상태부여(피해율34%,지력의영향),1턴지속",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "연인의포효",
    warLords: ["장비"],
    type: "패시브",
    target: "적군다수(3명)",
    percentage: "100%",
    desc: "전투시작후2,4번째턴에적군전체에게무기공격(피해율52%→104%),목표가무장해제상태이면추가로목표의통솔25%→50%감소,2턴지속.자신이주장일때통솔감소효과가허망상태의목표에게도추가",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "유혹",
    warLords: ["대교", "견희"],
    type: "패시브",
    target: "단일적군",
    percentage: "100%",
    desc: "자신이일반공격을받을때20%→40%의확률로공격자에게혼란(전법과관계없이목표선택해공격),허망(액티브전법발동불가),무장해제(일반공격불가),허약(피해주기불가)상태중1개부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "장구직입",
    warLords: ["서황"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중무기피해를줄때마다자신이주는무기피해7.5%→15%증가,최대5회중첩가능",
  },
  {
    rank: "S",
    skillName: "절대반격",
    warLords: ["하후돈", "여령기"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "(기병,방패병,창병전용)전투중자신이무기피해를받을때마다무력3→6증가,최대10회중첩가능.5번째턴의중첩횟수에따라적군전체에게무기피해부여(피해율60%→120%,매번피해율7%→14%증가)",
  },
  {
    rank: "S",
    skillName: "주지육림",
    warLords: ["동탁"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중턴마다자신의병력감소(1%X턴수),또한턴마다배반(무기피해를줄때자신의피해량을기준으로일정한병력회복)4%→8%및무력15회복.자신이주장이면5번째턴부터아군부장이살아있으면턴마다적군과아군전체에게무기피해(피해율30%→60%)",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "통렬한자중",
    warLords: ["정보"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "피해를받을때20%→35%확률로자신의디버프를정화하며,랜덤단일적군대상이공포상태에들어가게하고(이동불가),1턴이지속됩니다.이효과는매턴에최대한번을촉발할수있습니다.",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "호치",
    warLords: ["허저"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중턴마다단일적군대상을선택하여피해고정및대상에게주는피해16.5%→33%증가,목표를격파하면전투가끝날때까지자신이적진격파상태획득(피해를줄때목표의통솔과지력무시)",
  },
  {
    rank: "S",
    skillName: "흩뿌려진피",
    warLords: ["마초"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중자신의무력17→34및범위공격(일반공격시목표와같은부대의다른장수에게피해부여)효과27%→54%획득.자신이주장이면범위공격치30%→60%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "병력소집",
    warLords: ["서황", "원소"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "전투중자신이휴식상태를획득하여턴마다일정병력회복(회복률62%→124%)",
  },
  {
    rank: "S",
    skillName: "봉시진",
    warLords: ["황월영", "악진"],
    type: "진법",
    target: "아군다수(3명)",
    percentage: "100%",
    desc: "전투중아군주장이주는피해와책략피해15%→30%증가,받는무기피해와책략피해20%증가.아군부장이주는무기피해와책략피해15%감소,받는무기피해와책략피해12.5%→25%감소",
  },
  {
    rank: "S",
    skillName: "팔문금쇄진",
    warLords: ["조인"],
    type: "진법",
    target: "적군다수(2명)",
    percentage: "100%",
    desc: "전투시작후3번째턴까지적군다수대상(2명)이주는피해15%→30%감소(지력의영향)및아군주장이선공효과(우선행동)획득",
  },
  {
    rank: "S",
    skillName: "고지악래",
    warLords: ["전위"],
    type: "지휘",
    target: "아군주장",
    percentage: "100%",
    desc: "아군주장이일반공격을받을때자신이공격자에게맹격1회시전(피해율40%→80%),주는무기피해9%→18%감소,1턴지속,그후아군주장의일반공격분담",
  },
  {
    rank: "S",
    skillName: "공신",
    warLords: ["황월영"],
    type: "지휘",
    target: "아군다수(3명)",
    percentage: "100%",
    desc: "전투시작후3번째턴까지아군전체가선공상태(우선행동)획득,아군주장이주는피해15%→30%증가,아군부장이주는피해7.5%→15%증가.4번째턴부터아군전체가주는피해15%감소,2턴지속",
  },
  {
    rank: "S",
    skillName: "금단의비술",
    warLords: ["좌자"],
    type: "지휘",
    target: "아군다수(3명)",
    percentage: "100%",
    desc: "전투시작후2번째턴까지아군전체가모면효과를17.5%→35%획득하여피해면역,3번째턴부터휴식상태획득(턴마다병력1회회복,회복률29%→58%,지력의영향),3턴지속",
  },
  {
    rank: "S",
    skillName: "기세등등",
    warLords: ["안량", "조비"],
    type: "지휘",
    target: "적군다수(2명)",
    percentage: "100%",
    desc: "전투시작후2번째턴까지적군다수대상(2명)에게턴마다45%→90%의확률로무장해제상태부여,대상일반공격불가",
  },
  {
    rank: "S",
    skillName: "꺽인기세",
    warLords: ["손견", "진군"],
    type: "지휘",
    target: "단일적군",
    percentage: "100%",
    desc: "전투시작후3번째턴까지단일적군대상에게허약상태부여,피해를줄때32.5%→65%의확률로피해부여불가",
  },
  {
    rank: "S",
    skillName: "꿈속의처단",
    warLords: ["조조"],
    type: "지휘",
    target: "자신",
    percentage: "100%",
    desc: "전투시작후2번째턴까지자신이주장이면랜덤의부장이자신의피해20%→40%분담,3번째턴부터자신이행동시디버프가있으면25%→50%확률로전투종료때까지반격상태획득(피해율150%)",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "난세의간웅",
    warLords: ["조조"],
    type: "지휘",
    target: "아군다수(3명)",
    percentage: "100%",
    desc: "전투중우군다수대상(2명)이주는피해8%→16%증가(지력의영향),자신이받는피해9%→18%감소(지력의영향).자신이주장이면부장이피해를줄때해당피해량의10%만큼병력회복",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "대설전",
    warLords: ["제갈량"],
    type: "지휘",
    target: "적군다수(3명)",
    percentage: "100%",
    desc: "적군이액티브전법발동시15%→25%의확률로해당적군의발동률5%감소(지력의영향)및자신과랜덤우군의액티브전법발동률2%→4%증가(지력의영향),1턴지속",
  },
  {
    rank: "S",
    skillName: "백의도강",
    warLords: ["여몽"],
    type: "지휘",
    target: "자신",
    percentage: "100%",
    desc: "전투시작후첫번째턴에아군전체가방어1회획득.자신이무기공격시20%→40%의확률로단일적군대상에게무장해제(일반공격불가)부여,2턴지속.책략피해를줄때20%→40%의확률로단일적군대상에게허망(액티브전법발동불가)부여,1턴지속,해당효과는턴마다각각최대1회발동가능",
  },
  {
    rank: "S",
    skillName: "세상에가득찬덕",
    warLords: ["유비"],
    type: "지휘",
    target: "아군다수(2명)",
    percentage: "100%",
    desc: "턴마다아군다수를치료(2명,치료율34%→68%,지력의영향)하고5%→10%의확률로적군단일대상에게허약상태(피해주기불가)부여,1턴지속.자신이주장이면허약상태의부여확률이12.5%→25%까지증가",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "수이필고",
    warLords: ["정욱", "조식"],
    type: "지휘",
    target: "적군주장",
    percentage: "100%",
    desc: "전투시작시적군주장을도발하고(목표가자신을일반공격)자신의통솔20→40증가,4턴지속",
  },
  {
    rank: "S",
    skillName: "신기묘산",
    warLords: ["제갈량"],
    type: "지휘",
    target: "적군다수(2명)",
    percentage: "100%",
    desc: "적군다수대상(2명)이액티브전법발동시25%→35%의확률로패배및대상에게책략피해부여(피해율100%,지력의영향).자신이주장이면해당피해가양측의지력의차에따라추가로증가",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "신묘한술법",
    warLords: ["우길"],
    type: "지휘",
    target: "적군다수(3명)",
    percentage: "100%",
    desc: "전투시작후2번째턴부터적군전체에게수공상태부여,턴마다지속피해(피해율36%→72%,지력의영향),5턴지속",
  },
  {
    rank: "S",
    skillName: "십승실패",
    warLords: ["곽가"],
    type: "지휘",
    target: "우군주장",
    percentage: "100%",
    desc: "전투시작후2번째턴까지아군주장이통찰상태(모든제어효과에면역)획득,받는피해25%→50%감소",
  },
  {
    rank: "S",
    skillName: "의심소열",
    warLords: ["유비"],
    type: "지휘",
    target: "아군다수(3명)",
    percentage: "100%",
    desc: "전투중자신이치료효과를부여할때목표가받는액티브전법피해가7%→14%(지력의영향)감소,1턴지속.자신의병력이처음으로30%→40%미만일때아군전체가피해를받으면25%→50%분담,1턴지속",
  },
  {
    rank: "S",
    skillName: "잠피기봉",
    warLords: ["방덕", "서서"],
    type: "지휘",
    target: "아군다수(2명)",
    percentage: "100%",
    desc: "전투시작후3번째턴까지아군중지력이가장높은장수가받는무기피해20%→40%감소(지력의영향),아군중무력이가장높은장수가받는책략피해20%→40%감소(지력의영향)",
  },
  {
    rank: "S",
    skillName: "좌단동남",
    warLords: ["손권"],
    type: "지휘",
    target: "자신",
    percentage: "100%",
    desc: "전투중자신과우군의단일대상이일반공격을발동하면자신이37.5%→75%의확률로연격,통찰,선공,필중,적진격파상태중1개를랜덤획득,2턴지속.자신이주장이면우선적으로다른상태획득",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "청낭",
    warLords: ["화타"],
    type: "지휘",
    target: "아군다수(2명)",
    percentage: "100%",
    desc: "전투시작후4번째턴까지아군다수대상(2명)이통솔20→40(지력의영향)과구급효과획득,매회피해를받을때50%확률로일정한병력회복(치료율44%→88%,지력의영향)",
  },
  {
    rank: "S",
    skillName: "화신의기개",
    warLords: ["축융부인"],
    type: "지휘",
    target: "아군다수(2명)",
    percentage: "100%",
    desc: "전투시작후2번째턴까지아군다수대상(2명)이필중상태획득,3번째턴에허약상태(피해주기불가)면역및자신의매턴행동전에아군다수대상치료(2명,치료율79%→158%,무력의영향),3턴지속",
  },
  {
    rank: "S",
    skillName: "강동맹호",
    warLords: ["손견"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "50%",
    desc: "적군다수대상(2명)에게무기피해63%→126%및도발(목표가자신을일반공격),2턴지속",
  },
  {
    rank: "S",
    skillName: "경국의미인",
    warLords: ["초선"],
    type: "액티브",
    target: "적군다수(1~2명)",
    percentage: "25%→40%",
    desc: "1턴준비후적군다수대상(1~2명)에게혼란상태부여(전법과관계없이목표선택해공격)및50%의확률로아군다수대상(2명)이받는피해8%→16%감소,2턴지속,자신이여성이면반드시적군의다수대상(2명)선택",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "고육계",
    warLords: ["황개"],
    type: "액티브",
    target: "단일적군",
    percentage: "40%",
    desc: "자신에게무기피해를주고(피해율40%)단일적군대상에게연소(피해율61%→122%,지력의영향)와혼란(전법과관계없이목표를선택해공격)상태부여및자신이받는무기피해15%→30%감소,2턴지속",
  },
  {
    rank: "S",
    skillName: "관우의상처",
    warLords: ["화타"],
    type: "액티브",
    target: "단일아군",
    percentage: "40%",
    desc: "병력손실이가장많은단일아군대상의디버프해제및병력회복(치료율128%→256%,지력의영향)",
  },
  {
    rank: "S",
    skillName: "굳건한군대",
    warLords: ["우금"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "35%",
    desc: "자신이다음에받는무기피해가40%증가,1턴지속.자신의무력28→56증가,3턴지속.또한적군다수대상(2명)에게맹렬한일격발동(피해율92%→184%)",
  },
  {
    rank: "S",
    skillName: "굳건한마음",
    warLords: ["서서"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "35%",
    desc: "적군다수대상(2명)이30%→60%의확률로연소(지력의영향),중독(지력의영향),패배(무력의영향)상태랜덤획득,턴마다지속피해(피해율70%),상태마다독립판정,2턴지속",
  },
  {
    rank: "S",
    skillName: "깔끔한계책",
    warLords: ["종회"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "45%",
    desc: "1턴준비후적군2명에게책략공격(피해율105%→210%,지력의영향)및무장해제(일반공격불가),2턴지속",
  },
  {
    rank: "S",
    skillName: "난공불락",
    warLords: ["조인"],
    type: "액티브",
    target: "자신",
    percentage: "35%→45%",
    desc: "자신이통찰상태(모든제어효과면역)획득및적군전체도발(목표가자신에게일반공격),또한자신의통솔75→150증가,2턴지속",
  },
  {
    rank: "S",
    skillName: "대륙의위세",
    warLords: ["관우"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "35%",
    desc: "1턴준비후적군전체에게맹공(피해율73%→146%)및대상에게랜덤으로무장해제(일반공격불가)또는허망(액티브전법발동불가)부여,1턴지속.자신이주장일때추가로자신이주는무기피해18%→36%증가,2턴지속",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "독주",
    warLords: ["이유"],
    type: "액티브",
    target: "단일적군",
    percentage: "70%",
    desc: "단일적군대상에게독주를시전하여대상의무력30%→60%감소(지력의영향),1턴지속,1턴후독이퍼져책략공격발동(피해율113%→226%,지력의영향)및대상의통솔30→60감소(지력의영향),전투종료까지무제한중첩가능",
  },
  {
    rank: "S",
    skillName: "맹렬한불길",
    warLords: ["육손"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "35%",
    desc: "1턴준비후적군전체에게화공(피해율51%→102%,지력의영향)및연소상태부여,턴마다지속피해(피해율36%→72%,지력의영향),2턴지속",
  },
  {
    rank: "S",
    skillName: "목숨건전투",
    warLords: ["방덕"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "30%",
    desc: "1턴준비후적군다수대상(2명)의버프를해제하고무기공격(피해율127.5%→255%)",
  },
  {
    rank: "S",
    skillName: "무한한충성",
    warLords: ["전풍"],
    type: "액티브",
    target: "적군다수(1~2명)",
    percentage: "35%→50%",
    desc: "1턴준비후적군다수대상(1~2명)의속도15%감소(지력의영향)및혼란상태(전법과관계없이목표선택해공격)부여,2턴지속.또한우군단일대상이방어1회획득,1턴지속",
  },
  {
    rank: "S",
    skillName: "백발백중",
    warLords: ["황충"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "35%",
    desc: "1턴준비후자신의회심확률12.5%→25%증가(발동시무기피해100%증가),2턴지속.이후적군전체에게무기공격(피해율90%→180%),목표가제어상태일경우이번무기공격더욱강화(피해율120%→240%)",
  },
  {
    rank: "S",
    skillName: "병봉",
    warLords: ["장소", "맹획"],
    type: "액티브",
    target: "아군다수(2명)",
    percentage: "25%→35%",
    desc: "자신과우군단일대상이연격(턴마다일반공격2회가능)상태획득,1턴지속",
  },
  {
    rank: "S",
    skillName: "분노한창",
    warLords: ["장비"],
    type: "액티브",
    target: "자신",
    percentage: "40%",
    desc: "(기병,방패병,창병,병기전용)자신이무력25→50증가및범위공격(일반공격시목표와같은부대의다른장수에게피해부여)획득(피해율35%→70%),2턴지속",
  },
  {
    rank: "S",
    skillName: "불난데부채질",
    warLords: ["주유", "황개"],
    type: "액티브",
    target: "단일적군",
    percentage: "45%",
    desc: "단일적군대상에게책략피해(피해율77%→154%,지력의영향),목표가연소상태이면추가로책략피해1회(피해율99%→198%,지력의영향)",
  },
  {
    rank: "S",
    skillName: "사면초가",
    warLords: ["순욱", "이유"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "50%",
    desc: "1턴준비후적군다수대상(2명)에게중독상태를시전하여턴마다지속피해(피해율72%→144%,지력의영향),2턴지속",
  },
  {
    rank: "S",
    skillName: "사자분신",
    warLords: ["여령기"],
    type: "액티브",
    target: "적군다수(2~3명)",
    percentage: "35%",
    desc: "단일적군대상및추가로적군1~2명에게무기공격(피해율59%→118%),자신의액티브전법발동률5%→10%증가(자신이주장일때발동률7.5%→15%까지증가),2턴지속,단일대상의목표가적군주장이면대산에게모반상태부여,턴마다지속피해(피해율51%→102%,무력또는지력중높은항목의영향을받고방어무시),2턴지속",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "십면매복",
    warLords: ["정욱"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "35%",
    desc: "디버프상태의적군에게책략공격(피해율48%→96%,지력의영향)후,적군다수대상(2명)에게치료금지(병력회복불가)및모반상태를부여하여턴마다지속피해(피해율37%→74%,무력또는지력중높은항목의영향을받고방어무시),2턴지속",
  },
  {
    rank: "S",
    skillName: "양동작전",
    warLords: ["등애"],
    type: "액티브",
    target: "단일적군",
    percentage: "25%→50%",
    desc: "1턴준비후단일적군대상에게책략공격(피해율260%,지력의영향)및공포상태(행동불가)부여,2턴지속",
  },
  {
    rank: "S",
    skillName: "와신상담",
    warLords: ["손권"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "45%",
    desc: "적군다수대상(2명)에게무기공격1회(피해율48%→96%)및25%의확률로(자신의연격,통찰,선공,필증,적진격파상태가1개증가할때마다확률5%→10%증가)공포상태(행동불가)부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "용감무쌍",
    warLords: ["문추"],
    type: "액티브",
    target: "단일적군",
    percentage: "55%",
    desc: "단일대상목표에게무기공격(피해율104%→208%)및무장해제(일반공격불가),자신의통솔40%감소및치료금지상태(병력회복불가)부여,2턴지속",
  },
  {
    rank: "S",
    skillName: "유인책",
    warLords: ["사마휘", "화웅"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "40%",
    desc: "1턴준비후적군다수대상(2명)에게모래폭풍상태부여,턴마다지속피해(피해율63%→126%,지력의영향)및대상이받는무기피해25%증가,2턴지속",
  },
  {
    rank: "S",
    skillName: "의심암귀",
    warLords: ["좌자", "우길"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "50%",
    desc: "1턴준비후적군다수대상(2명)에게책략공격1회(피해율76.5%→153%)및아군다수대상(2명)의일정한병력회복(회복률51%→102%,지력의영향)",
  },
  {
    rank: "S",
    skillName: "이어지는명성",
    warLords: ["원소"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "50%",
    desc: "1턴준비후적군다수대상(2명)에게무기공격1회(피해율63%→126%),대상의통솔12→24감소(무력의영향)및연소상태를부여하여턴마다지속피해(피해율30%→60%,지력의영향),2턴지속.자신이주장이면추가로아군전체의통솔40→80%증가,3턴지속",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "이일대로",
    warLords: ["법정"],
    type: "액티브",
    target: "아군다수(2명)",
    percentage: "35%",
    desc: "아군다수대상치료(2명,치료율77%→154%,지력의영향)및다음3회피해에서받는피해감소(각각25%→50%,18.8%→37.5%,12.5%→25%),지력의영향)다음제어상태에25%→40%의확률(지력의영향)로면역",
  },
  {
    rank: "S",
    skillName: "일망타진",
    warLords: ["관우", "조운"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "40%",
    desc: "적군전체에게무기피해50%→100%부여,목표가무장해제또는허망상태이면20%→30%의확률로목표에게공포상태(행동불가)부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "일망타진",
    warLords: ["관우", "조운"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "40%",
    desc: "적군전체에게무기피해50%→100%부여,목표가무장해제또는허망상태이면20%→30%의확률로목표에게공포상태(행동불가)부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "일제사격",
    warLords: ["황충", "하후연"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "40%",
    desc: "(궁병전용)1턴준비후적군전체에게무기공격발동(피해율70%→140%)및50%의확률로패배상태를부여하여턴마다지속피해(피해율60%→120%,무력의영향),1턴지속",
  },
  {
    rank: "S",
    skillName: "임전선동",
    warLords: ["악진"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "100%",
    desc: "적군다수대상(2명)에게무기공격(피해율67.5%→135%)후자신에게허약상태(피해주기불가)부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "적진함락",
    warLords: ["손책", "문추"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "35%",
    desc: "1턴준비후적군다수대상(2명)의통솔,지력40→80감소(무력의영향),2턴지속및대상에게무기공격1회(피해율79%→158%)",
  },
  {
    rank: "S",
    skillName: "천하무쌍",
    warLords: ["여포"],
    type: "액티브",
    target: "단일적군",
    percentage: "25%→35%",
    desc: "단일적군대상에게결투를요청하여양측이순서대로상대방에게일반공격3회가함,자신이우선공격진행.결투중양측은무장해제와공포상태에영향을받지않고범위공격과돌격전법발동가능.자신이주장이면결투후자신이받는무기피해3.5%→7%감소(무력의영향),2턴지속",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "천하무적",
    warLords: ["마초", "허저"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "30%",
    desc: "(기병,방패병,창병,병기전용)1턴준비후적군전체에게무기공격1회(피해율102.4%→204.8%)",
  },
  {
    rank: "S",
    skillName: "청천벽력",
    warLords: ["장각"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "45%",
    desc: "1턴준비후적군랜덤단일대상에게책략공격(피해율51%→102%,지력의영향),총5회발동하며매번별도로목표선택.목표가수공상태이면30%확률로공토상태부여(행동불가),1턴지속.자신이주장이면공포의확률50%증가및모래폭풍상태에유효",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "침사결수",
    warLords: ["곽가", "법정"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "40%",
    desc: "1턴준비후적군다수대상(2명)에게수공상태부여,턴마다지속피해(피해율63%→126%,지력의영향을받음)및대상이받는책략피해25%증가,2턴지속",
  },
  {
    rank: "S",
    skillName: "폐월",
    warLords: ["초선"],
    type: "액티브",
    target: "단일적군",
    percentage: "40%→75%",
    desc: "적군1명을선택하여자신의피해12.5%→25%분담(지력의영향).목표가적군중무력이가장높으면혼란상태부여(전법과관계없이목표선택해공격),목표가적군중지력이가장높으면허망상태부여(액티브전법발동불가)또는허약(피해주기불가)과치료금지(병력회복불가)상태부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "호가의소리",
    warLords: ["채문희"],
    type: "액티브",
    target: "아군다수(2명)",
    percentage: "50%",
    desc: "아군다수대상치료(2명,치료율61%→122%,지력의영향)및자신과우군의단일대상이받는피해13%→26%감소(지력의영향),2턴지속",
  },
  {
    rank: "S",
    skillName: "호전적군웅",
    warLords: ["화웅"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "35%",
    desc: "1턴준비후적군다수대상(2명)에게무기공격1회(피해율100%→200%),이후자신이주는무기피해12.5%→25%증가,받는무기피해감소(12.5%→25%,무력의영향),2턴지속",
  },
  {
    rank: "S",
    skillName: "혼비백산",
    warLords: ["소교", "채문희"],
    type: "액티브",
    target: "단일적군",
    percentage: "55%",
    desc: "단일적군대상의무력,지력,속도,통솔19→38훔치기(지력의영향을받음),2턴지속,2회중첩가능",
  },
  {
    rank: "S",
    skillName: "화소연영",
    warLords: ["육손"],
    type: "액티브",
    target: "단일적군",
    percentage: "50%",
    desc: "단일적군대상에게연소상태(피해율41%→82%,지력의영향)부여,3턴지속,랜덤으로2회부여.만약이미연소상태의목표일경우적군전체에책략공격(31%→62%,지력의영향,자신을주장으로할때,피해율이49%→98%까지증가),또한30%확률로연소상태의적군에위협상태부여,1턴지속,이후또다른적군에게연소상태부여",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "황천태평",
    warLords: ["장각"],
    type: "액티브",
    target: "적군다수",
    percentage: "(2명)",
    desc: "25%→35%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "대극사",
    warLords: ["장합"],
    type: "장합",
    target: "병종",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "등갑병",
    warLords: ["올돌골"],
    type: "올돌골",
    target: "병종",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "무당비군",
    warLords: ["왕평"],
    type: "왕평",
    target: "병종",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "백마의종",
    warLords: ["공손찬"],
    type: "공손찬",
    target: "병종",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "백이병",
    warLords: ["진도"],
    type: "진도",
    target: "병종",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "서량의철기",
    warLords: ["마등"],
    type: "마등",
    target: "병종",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "함진영",
    warLords: ["고순"],
    type: "고순",
    target: "병종",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "호표기",
    warLords: ["조순"],
    type: "조순",
    target: "병종",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "극악무도",
    warLords: ["동탁"],
    type: "돌격",
    target: "단일적군",
    percentage: "25%→35%",
    desc: "일반공격후공격목표에게추가로무기공격1회(피해율196%)및혼란상태(전법과관계없이목표선택해공격)부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "극적제승",
    warLords: ["정보", "우금"],
    type: "돌격",
    target: "단일적군",
    percentage: "40%",
    desc: "일반공격후공격목표에게추가로책략피해1회(피해율90%→180%,지력의영향),목표가패배나중독상태이면70%의확률로목표에게허약상태(피해주기불가)부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "삼군의으뜸",
    warLords: ["안량"],
    type: "돌격",
    target: "단일적군",
    percentage: "30%",
    desc: "일반공격후공격목표에게추가로맹공(피해율90%→180%)및공포상태(행동불가)부여,1턴지속",
  },
  {
    rank: "S",
    skillName: "일기당천",
    warLords: ["여포"],
    type: "돌격",
    target: "적군다수(3명)",
    percentage: "30%",
    desc: "일반공격후적군전체에게무기공격1회(피해율36%→72%).자신이주장이면해당무기공격이더욱강력하게변화(피해율54%→108%)",
    hasCaptainImpact: true,
  },
  {
    rank: "S",
    skillName: "장수의속도",
    warLords: ["하후연"],
    type: "돌격",
    target: "단일적군",
    percentage: "30%→60%",
    desc: "일반공격후랜덤의단일적군대상에게무기공격1회(피해율158%),적군주장을명중시키면허망상태부여가능(액티브전법발동불가),2턴지속",
  },
  {
    rank: "S",
    skillName: "적군제압",
    warLords: ["태사자", "전위"],
    type: "돌격",
    target: "단일적군",
    percentage: "25%→45%",
    desc: "일반공격후랜덤단일적군대상의통솔과지력100감소,2턴지속.자신이주장이아니면추가로아군주장이방어2회획득,피해면역가능,2턴지속",
  },
  {
    rank: "S",
    skillName: "적진습격",
    warLords: ["감녕"],
    type: "돌격",
    target: "단일적군",
    percentage: "40%",
    desc: "(기병전용)일반공격후랜덤의단일적군대상에게무기공격1회(피해율81%→162%)및50%의확률로적군주장에게무기공격1회(피해율60%→120%)",
  },
  {
    rank: "S",
    skillName: "공훈거사",
    warLords: ["장소"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를주정관으로임명하면전체자원의생산량1.3%→2.5%증가",
  },
  {
    rank: "S",
    skillName: "고고한명성",
    warLords: ["진군"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를제철관으로임명하면철광생산량1.5%→3%증가",
  },
  {
    rank: "S",
    skillName: "나라의발전",
    warLords: ["조비"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "주정관을임명하면건물레벨업시간15%→30%감소",
  },
  {
    rank: "S",
    skillName: "수경선생",
    warLords: ["사마휘"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를탐방사로임명하면고급보상을찾을확률4.5%증가",
  },
  {
    rank: "S",
    skillName: "왕좌지재",
    warLords: ["순욱"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수의정치36→72증가",
  },
  {
    rank: "S",
    skillName: "절세미인",
    warLords: ["대교"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를무역관으로임명하면무역비율1.5%→3%증가",
  },
  {
    rank: "S",
    skillName: "칠보성시",
    warLords: ["조식"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를단조관으로임명하면고급장비단조확률4.5%→9%증가",
  },
  {
    rank: "S",
    skillName: "타고난미모",
    warLords: ["소교"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수의매력13.5%→27%증가",
  },
  {
    rank: "S",
    skillName: "화용월태",
    warLords: ["견희"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를훈련사로임명하면훈련경험치획득3%→6%증가",
  },
  {
    rank: "A",
    skillName: "굳센의지",
    warLords: ["주창"],
    type: "주창",
    target: "패시브",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "백동성강",
    warLords: ["여범", "서성"],
    type: "패시브",
    target: "자신",
    percentage: "100%",
    desc: "자신의무력,지력,통솔,속도18→36증가",
  },
  {
    rank: "A",
    skillName: "백미",
    warLords: ["마량"],
    type: "마량",
    target: "패시브",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "분투",
    warLords: ["관평"],
    type: "관평",
    target: "패시브",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "자가치유",
    warLords: ["동습"],
    type: "동습",
    target: "패시브",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "침착한대응",
    warLords: ["황보숭"],
    type: "황보숭",
    target: "패시브",
    percentage: "단일적군",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "거짓항복",
    warLords: ["요화"],
    type: "요화",
    target: "지휘",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "대항의자벽",
    warLords: ["곽회"],
    type: "곽회",
    target: "지휘",
    percentage: "아군다수(2명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "장자의바람",
    warLords: ["이만성"],
    type: "이만성",
    target: "지휘",
    percentage: "아군다수(3명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "진퇴양난",
    warLords: ["유봉"],
    type: "유봉",
    target: "지휘",
    percentage: "적군다수(2명)",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "황건적평정",
    warLords: ["주준"],
    type: "지휘",
    target: "양측전체",
    percentage: "100%",
    desc: "전투시작후2번째턴에아군전체에게모래폭풍면역상태부여,적군전체는모반상태가되어턴마다지속피해(피해율44%→88%,무력또는지력중높은항목의영향을받고방어무시),2턴지속,목표가황건군이면피해율20%증가",
  },
  {
    rank: "A",
    skillName: "가혹한세금",
    warLords: ["곽사"],
    type: "곽사",
    target: "액티브",
    percentage: "단일적군",
    desc: "45%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "강공",
    warLords: ["간옹", "기령"],
    type: "액티브",
    target: "액티브",
    percentage: "25%→45%",
    desc: "자신에게연격상태부여(턴마다일반공격2회가능),1턴지속",
  },
  {
    rank: "A",
    skillName: "겁쟁이",
    warLords: ["종요", "봉기"],
    type: "액티브",
    target: "적군다수",
    percentage: "45%",
    desc: "1턴준비후적군다수대상(2명)에게책략공격(피해율52.5%→105%,지력의영향)과모래폭풍상태부여,턴마다지속피해(피해율60%→120%,지력의영향),1턴지속",
  },
  {
    rank: "A",
    skillName: "격렬한설전",
    warLords: ["왕랑"],
    type: "왕랑",
    target: "액티브",
    percentage: "적군다수(3명)",
    desc: "50%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "겸양",
    warLords: ["공융"],
    type: "공융",
    target: "액티브",
    percentage: "단일아군",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "고성사수",
    warLords: ["심배"],
    type: "심배",
    target: "액티브",
    percentage: "아군다수(2명)",
    desc: "45%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "낙뢰",
    warLords: ["진림"],
    type: "액티브",
    target: "기타단일",
    percentage: "50%",
    desc: "랜덤의기타단일대상(5%의확률로우군에게시전)에게책략공격(피해율85%→170%,지력의영향)및대상이받는책략피해9%→18%증가,2턴지속",
  },
  {
    rank: "A",
    skillName: "낙봉",
    warLords: ["장임"],
    type: "장임",
    target: "액티브",
    percentage: "단일적군",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "뛰어난기량",
    warLords: ["마속"],
    type: "마속",
    target: "액티브",
    percentage: "아군다수(2명)",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "무모",
    warLords: ["관해"],
    type: "관해",
    target: "액티브",
    percentage: "자신",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "무차별도륙",
    warLords: ["조진"],
    type: "조진",
    target: "액티브",
    percentage: "단일적군",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "백병전",
    warLords: ["정봉"],
    type: "정봉",
    target: "액티브",
    percentage: "단일적군",
    desc: "40%",
    hasCaptainImpact: true,
  },
  { rank: "A", skillName: "복배수적", warLords: ["봉기"]},
  {
    rank: "A",
    skillName: "불벼락",
    warLords: ["장흠"],
    type: "장흠",
    target: "액티브",
    percentage: "적군다수(2명)",
    desc: "50%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "불의의습격",
    warLords: ["보연사"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "20%→35%",
    desc: "1턴준비후적군다수대상(2명)에게랜덤으로허망(액티브전법공격불가)또는무장해제(일반공격불가)부여,1~2턴지속(30%의확률로2턴지속)",
  },
  {
    rank: "A",
    skillName: "사명완수",
    warLords: ["반장"],
    type: "반장",
    target: "액티브",
    percentage: "단일적군",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "성동격서",
    warLords: ["동윤", "주준"],
    type: "액티브",
    target: "적군다수(2명)",
    percentage: "40%",
    desc: "1턴준비후적군다수대상(2명)에게책략공격(피해율87.5%→175%,지력의영향)및속도15→30감소,2턴지속",
  },
  {
    rank: "A",
    skillName: "세찬동향",
    warLords: ["장수"],
    type: "장수",
    target: "액티브",
    percentage: "단일적군",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "신상사",
    warLords: ["장만성"],
    type: "장만성",
    target: "액티브",
    percentage: "적군다수(3명)",
    desc: "50%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "약점간파",
    warLords: ["장패"],
    type: "장패",
    target: "액티브",
    percentage: "단일적군",
    desc: "50%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "여상의상갑",
    warLords: ["진무"],
    type: "진무",
    target: "액티브",
    percentage: "우군단일",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "요술",
    warLords: ["장보"],
    type: "장보",
    target: "액티브",
    percentage: "적군다수(3명)",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "용감한제비",
    warLords: ["장연"],
    type: "장연",
    target: "액티브",
    percentage: "단일적군",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "용맹한행군",
    warLords: ["호거아"],
    type: "호거아",
    target: "액티브",
    percentage: "단일적군",
    desc: "45%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "위풍당당",
    warLords: ["기령"],
    type: "액티브",
    target: "적군다수(1~2명)",
    percentage: "30%→45%",
    desc: "단일적군대상에게도발(목표가자신을일반공격)또는무장해제(일반공격불가)상태부여,2턴지속,37.5%→75%의확률로추가시전1회",
  },
  {
    rank: "A",
    skillName: "의성",
    warLords: ["서성"],
    type: "액티브",
    target: "자신",
    percentage: "75%",
    desc: "자신의혼란상태면역및무력34→68증가,2턴지속",
  },
  {
    rank: "A",
    skillName: "일격섬멸",
    warLords: ["장량"],
    type: "장량",
    target: "액티브",
    percentage: "단일적군",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "전투의귀재",
    warLords: ["조홍"],
    type: "조홍",
    target: "액티브",
    percentage: "단일적군",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "정화",
    warLords: ["이엄"],
    type: "액티브",
    target: "아군다수",
    percentage: "30%→45%",
    desc: "아군다수대상(2명)의무력,지력,속도12→24증가,2턴지속및디버프해제",
  },
  {
    rank: "A",
    skillName: "정확한예측",
    warLords: ["유엽"],
    type: "유엽",
    target: "액티브",
    percentage: "적군다수(2명)",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "좌우개궁",
    warLords: ["한당"],
    type: "한당",
    target: "액티브",
    percentage: "단일적군",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "좌절의습격",
    warLords: ["조창"],
    type: "조창",
    target: "액티브",
    percentage: "적군다수(2명)",
    desc: "25%→35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "진언",
    warLords: ["곽도"],
    type: "곽도",
    target: "액티브",
    percentage: "우군단일",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "천리의구원",
    warLords: ["주환"],
    type: "주환",
    target: "액티브",
    percentage: "우군다수(2명)",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "추방",
    warLords: ["마철"],
    type: "액티브",
    target: "적군다수(3명)",
    percentage: "30%→45%",
    desc: "적군전체의버프해제및자신의지력14→28증가,3턴지속",
  },
  {
    rank: "A",
    skillName: "출병약탈",
    warLords: ["이각"],
    type: "이각",
    target: "액티브",
    percentage: "단일적군",
    desc: "35%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "화려한기략",
    warLords: ["황권"],
    type: "황권",
    target: "액티브",
    percentage: "적군다수(2명)",
    desc: "45%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "휴전",
    warLords: ["비의", "유표"],
    type: "액티브",
    target: "단일적군",
    percentage: "40%",
    desc: "1턴준비후아군다수대상(2명)의책략피해12.5%→25%증가,1턴지속.이후단일적군대상에게책략공격(피해율105%→210%,지력의영향)",
  },
  {
    rank: "A",
    skillName: "날렵한칼날",
    warLords: ["문빙"],
    type: "문빙",
    target: "돌격",
    percentage: "단일적군",
    desc: "30%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "숨겨진계책",
    warLords: ["한수"],
    type: "한수",
    target: "돌격",
    percentage: "단일적군",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "용맹한사수",
    warLords: ["사마가"],
    type: "사마가",
    target: "돌격",
    percentage: "단일적군",
    desc: "40%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "고아한정취",
    warLords: ["이엄"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를목재관으로임명하면목재생산량1%→2%증가",
  },
  {
    rank: "A",
    skillName: "고지식",
    warLords: ["마철"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를조련관으로임명하면명마생산확률2%→4%증가",
  },
  {
    rank: "A",
    skillName: "군대양성",
    warLords: ["제갈근"],
    type: "제갈근",
    target: "내정",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "뛰어난언변",
    warLords: ["양수"],
    type: "양수",
    target: "내정",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "묘서명석",
    warLords: ["간옹"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를채석관으로임명하면석재생산량1%→2%증가",
  },
  {
    rank: "A",
    skillName: "밝은통찰력",
    warLords: ["여범"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수의정치12→24증가",
  },
  {
    rank: "A",
    skillName: "빛나는쇠조각",
    warLords: ["종요"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를제철관으로임명하면철광둔전의수익1.5%→3%증가",
  },
  {
    rank: "A",
    skillName: "선견지명",
    warLords: ["비의"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를무역관으로임명하면무역비율1%→2%증가",
  },
  {
    rank: "A",
    skillName: "세심한보필",
    warLords: ["보연사"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를단조관으로임명하면단조소모2%→4%감소",
  },
  {
    rank: "A",
    skillName: "시급한사안",
    warLords: ["유표"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를조련관으로임명하면조련시간5%→10%감소",
  },
  {
    rank: "A",
    skillName: "임기응변",
    warLords: ["미축"],
    type: "미축",
    target: "내정",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "절차탁마",
    warLords: ["동윤"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를제철관으로임명하면철광생산량1%→2%증가",
  },
  {
    rank: "A",
    skillName: "절처봉생",
    warLords: ["고옹"],
    type: "고옹",
    target: "내정",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "조련의장인",
    warLords: ["장로"],
    type: "장로",
    target: "내정",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
  {
    rank: "A",
    skillName: "주렁주렁열매",
    warLords: ["진림"],
    type: "내정",
    target: "자신",
    percentage: "100%",
    desc: "장수를군량관으로임명하면식량생산량1%→2%증가",
  },
  {
    rank: "A",
    skillName: "풍성한오곡",
    warLords: ["노식"],
    type: "노식",
    target: "내정",
    percentage: "자신",
    desc: "100%",
    hasCaptainImpact: true,
  },
];

